pluginManagement{
    repositories{
        maven("https://maven.aliyun.com/repository/public")
        gradlePluginPortal()
        maven("https://maven.minecraftforge.net")
        maven("https://maven.fabricmc.net")
        maven("https://maven.neoforged.net/releases")
    }
}
include("forge","fabric","neoforge")